In [1]:
import folium
import geopandas as gpd

In [2]:
gpkg_file = r"C:\Users\PC\Downloads\kontur_population_MY_20220630.gpkg\kontur_population_MY_20220630.gpkg"
density_gdf = gpd.read_file(gpkg_file, layer='population')

In [3]:
json = r"C:\Users\PC\Downloads\geoBoundaries-MYS-ADM1_simplified.geojson"
json_gpd = gpd.read_file(json)

In [4]:
json_gpd

,shapeName,shapeISO,shapeID,shapeGroup,shapeType,geometry
0,Selangor,MY-10,15666254B13191325950550,MYS,ADM1,"MULTIPOLYGON (((101.24990 2.90772, 101.25593 2..."
1,Johor,MY-01,15666254B95627195804992,MYS,ADM1,"MULTIPOLYGON (((104.06240 2.21794, 104.06423 2..."
2,Kuala Lumpur,MY-14,15666254B97003483933575,MYS,ADM1,"POLYGON ((101.62807 3.13801, 101.62960 3.13681..."
3,Malacca,MY-04,15666254B53495315209756,MYS,ADM1,"MULTIPOLYGON (((102.31921 2.11145, 102.32427 2..."
4,Negeri Sembilan,MY-05,15666254B60207109163985,MYS,ADM1,"POLYGON ((101.70373 2.60886, 101.70243 2.60505..."
5,Sabah,MY-12,15666254B50242947747650,MYS,ADM1,"MULTIPOLYGON (((117.62919 4.20156, 117.63554 4..."
6,Sarawak,MY-13,15666254B17824011144250,MYS,ADM1,"MULTIPOLYGON (((110.29745 1.66348, 110.30178 1..."
7,Kelantan,MY-03,15666254B53971551003747,MYS,ADM1,"POLYGON ((101.69131 5.75510, 101.69052 5.74661..."
8,Putrajaya,MY-16,15666254B54729125478011,MYS,ADM1,"POLYGON ((101.68046 2.88052, 101.68062 2.88199..."
9,Terengganu,MY-11,15666254B66133841680983,MYS,ADM1,"MULTIPOLYGON (((103.67313 4.80327, 103.67751 4..."
10,Pahang,MY-06,15666254B9931075294568,MYS,ADM1,"POLYGON ((101.91502 3.25679, 101.92473 3.26698..."
11,Kedah,MY-02,15666254B40304163283793,MYS,ADM1,"MULTIPOLYGON (((99.72140 6.20837, 99.72257 6.2..."
12,Perlis,MY-09,15666254B44964481844598,MYS,ADM1,"POLYGON ((100.37185 6.53739, 100.36595 6.54005..."
13,Perak,MY-08,15666254B89869535683348,MYS,ADM1,"MULTIPOLYGON (((100.63654 4.15716, 100.63725 4..."
14,Penang,MY-07,15666254B8245728769125,MYS,ADM1,"MULTIPOLYGON (((100.33992 5.57710, 100.33822 5..."
15,Labuan,MY-15,15666254B4265207353082,MYS,ADM1,"MULTIPOLYGON (((115.13150 5.21699, 115.13707 5..."

In [5]:
density_gdf

,h3,population,geometry
0,888c929ac7fffff,3.0,"POLYGON ((12224048.234 164640.711, 12224112.00..."
1,888c929a8dfffff,1.0,"POLYGON ((12223672.570 165512.945, 12223736.33..."
2,888c929a89fffff,2.0,"POLYGON ((12223105.617 164718.852, 12223169.37..."
3,888c929a8dfffff,1.0,"POLYGON ((12223672.570 165512.945, 12223736.33..."
4,888c9298e9fffff,5.0,"POLYGON ((12222927.945 171463.516, 12222991.71..."
...,...,...,...
158149,886518325bfffff,951.0,"POLYGON ((11169039.734 742496.938, 11169090.89..."
158150,8865183253fffff,1566.0,"POLYGON ((11168611.094 743415.719, 11168662.25..."
158151,886518ad2dfffff,992.0,"POLYGON ((11168028.969 742581.500, 11168080.11..."
158152,886518ad67fffff,256.0,"POLYGON ((11168457.625 741662.719, 11168508.78..."
158153,886518ad63fffff,68.0,"POLYGON ((11167875.531 740828.531, 11167926.67..."

In [6]:
json_gpd = json_gpd.to_crs(density_gdf.crs)

In [7]:
pop_join = gpd.sjoin(density_gdf,json_gpd,predicate='intersects',how="inner")

In [8]:
pop_join

,h3,population,geometry,index_right,shapeName,shapeISO,shapeID,shapeGroup,shapeType
0,888c929ac7fffff,3.0,"POLYGON ((12224048.234 164640.711, 12224112.00...",6,Sarawak,MY-13,15666254B17824011144250,MYS,ADM1
1,888c929a8dfffff,1.0,"POLYGON ((12223672.570 165512.945, 12223736.33...",6,Sarawak,MY-13,15666254B17824011144250,MYS,ADM1
2,888c929a89fffff,2.0,"POLYGON ((12223105.617 164718.852, 12223169.37...",6,Sarawak,MY-13,15666254B17824011144250,MYS,ADM1
3,888c929a8dfffff,1.0,"POLYGON ((12223672.570 165512.945, 12223736.33...",6,Sarawak,MY-13,15666254B17824011144250,MYS,ADM1
4,888c9298e9fffff,5.0,"POLYGON ((12222927.945 171463.516, 12222991.71...",6,Sarawak,MY-13,15666254B17824011144250,MYS,ADM1
...,...,...,...,...,...,...,...,...,...
155318,88651d8d27fffff,2739.0,"POLYGON ((11180031.312 612994.938, 11180082.45...",14,Penang,MY-07,15666254B8245728769125,MYS,ADM1
155319,88651d8d1bfffff,1056.0,"POLYGON ((11176550.516 608010.250, 11176601.60...",14,Penang,MY-07,15666254B8245728769125,MYS,ADM1
155320,88651d8d17fffff,883.0,"POLYGON ((11176703.789 609754.500, 11176754.88...",14,Penang,MY-07,15666254B8245728769125,MYS,ADM1
155321,88651d8d13fffff,787.0,"POLYGON ((11176123.695 608923.719, 11176174.77...",14,Penang,MY-07,15666254B8245728769125,MYS,ADM1
155322,88651d8d11fffff,768.0,"POLYGON ((11177130.602 608841.000, 11177181.70...",14,Penang,MY-07,15666254B8245728769125,MYS,ADM1

In [9]:
def style_function(feature):
    return {'fillColor': '#ffffff', 'color': '#ffffff', 'fillOpacity': 0.0, 'stroke': False}

In [10]:
# Create a map centered on Kuala Lumpur
map = folium.Map(location=[3.1390, 101.6869], zoom_start=11, width=1000, height=1000)

# Add the intersect_gdf to the map as a GeoJSON layer
folium.GeoJson(pop_join).add_to(map)

# Display the map
map

In [11]:
folium.Choropleth(
    geo_data=pop_join,
    data=pop_join,
    columns=['h3', 'population'],
    key_on='feature.properties.h3',
    fill_color='YlOrRd',
    fill_opacity=0.7,
    line_opacity=0.1,
    legend_name='Population Density',
    highlight=True,
    style_function=style_function,
    tooltip = ['Population Density: ','population']
).add_to(map)

# Display the map
map

In [12]:
pop_join.to_csv("population_in_malaysia.csv", index=False)